/*
 * JMH Profilers based on "xctrace" utility
 * Copyright (C) 2023 Filipp Zhinkin
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package org.openjdk.jmh.profile;

import joptsimple.OptionException;
import joptsimple.OptionParser;
import joptsimple.OptionSpec;
import org.openjdk.jmh.infra.BenchmarkParams;
import org.openjdk.jmh.results.BenchmarkResult;
import org.openjdk.jmh.results.BenchmarkResultMetaData;
import org.openjdk.jmh.results.Result;
import org.openjdk.jmh.util.*;

import java.io.File;
import java.nio.file.Path;
import java.util.*;

/**
 * macOS permasm profiler based on xctrace utility shipped with Xcode Instruments.
 * Depending on the chosen tracing configuration, so-called template, xctrace may sample program counter
 * of a profiled process using either timer interrupts, or PMU interrupts.
 * <p>
 * The profiling process consists of several steps:
 * 1) launching a program that needs to be profiled using `xctrace record` command; in case of success,
 * the output of this step is a "trace-file", which is in fact a directory containing multiple files
 * representing the recorded trace, the trace may contain multiple resulting tables, depending on the template;
 * 2) inspecting a recorded trace to check if it contains a table supported by the profiler; this information
 * could be obtained from the trace's table of contents (`xctrace export --toc`);
 * 3) extracting the table with profiling results from the trace file using xctrace export and parsing it
 * to extract individual samples.
 * <p>
 * `xctrace export` command extracts data only in XML format, thus both the table of contents and the table
 * with profiling results need to be parsed as XML documents.
 * <p>
 * This profiler currently supports only three table types:
 * 1) time-profile tables generated by the Time Profiler instrument performing sampling by timer interrupts;
 * 2) cpu-profile tables generated by the CPU Profiler instrument performing sampling by the cycles PMU interrupts;
 * 3) counters-profile tables generated by the CPU Counters instrument performing sampling either by
 * timer interrupts, or interrupts generated by a PMU counter, depending on particular configuration.
 * <p>
 * Tracing configuration, or template, mentioned earlier is a file that could be configured and saved
 * using Instruments application. Unfortunately, there is no other way to set it up.
 * <p>
 * There are several builtin templates, and some of them, namely "Time Profiler" and "CPU Profiler", could be
 * used without any additional setup.
 *
 * TODO:
 * - output file setup looks terrible (xctrace need either path to an existing temporary directory and
 *   it'll create trace file inside it, or a non-existing path with ".trace" extension); JMH supports only
 *   temporary files, thus all the mess with perfBinFile.
 * - profiling results copying does not work, because the base class only supports file copying.
 */
public class XCTraceAsmProfiler extends AbstractPerfAsmProfiler {
    private final String template;
    private final boolean shouldFixStartTime;
    private OptionSpec<String> templateOpt;
    private OptionSpec<Boolean> correctOpt;
    private XCTraceTableDesc.TableType resultsTable;

    private long recordStartMs = 0;
    private long forkStartTimeMs = 0;

    /**
     * Parameterless constructor to allow loading the class via ServiceLoader
     * on all platforms. To initialize the profiler, JMH will use constructor accepting
     * a string first, that's where the ProfilerException will be thrown if the profiler
     * is not available on a target machine.
     * Without it, -lprof will fail on machines where xctrace is unavailable.
     */
    public XCTraceAsmProfiler() throws ProfilerException {
        super("");
        template = "";
        shouldFixStartTime = true;
    }

    public XCTraceAsmProfiler(String initLine) throws ProfilerException {
        super(initLine, "sampled_pc");
        XCTraceUtils.checkXCTraceWorks();
        try {
            template = set.valueOf(templateOpt);
            shouldFixStartTime = set.valueOf(correctOpt);
        } catch (OptionException e) {
            throw new ProfilerException(e.getMessage());
        }
        perfBinData.delete();
    }

    @Override
    protected void addMyOptions(OptionParser parser) {
        templateOpt = parser.accepts("template", "Path to or name of an Instruments template. " +
                        "Use `xctrace list templates` to view available templates.")
                .withOptionalArg().ofType(String.class).defaultsTo("CPU Profiler");
        correctOpt = parser.accepts("fixStartTime", "Fix the start time by the time it took to launch.")
                .withRequiredArg().ofType(Boolean.class).defaultsTo(true);
    }

    @Override
    protected void parseEvents() {
        Path profile = XCTraceUtils.findTraceFile(perfBinData.file().toPath());
        XCTraceUtils.exportTableOfContents(profile.toAbsolutePath().toString(), perfParsedData.getAbsolutePath());
        XCTraceTableOfContentsHandler handler = new XCTraceTableOfContentsHandler();
        handler.parse(perfParsedData.file());
        recordStartMs = handler.getRecordStartMs();
        List<XCTraceTableDesc> tables = handler.getSupportedTables();
        if (tables.isEmpty()) {
            throw new IllegalStateException("Profiling results does not contain table supported by this profiler.");
        }
        if (tables.size() != 1) {
            throw new IllegalStateException("There are multiple supported tables in output, " +
                    "please specify which one to use using \"table\" option");
        }
        resultsTable = tables.get(0).getTableType();
        XCTraceUtils.exportTable(profile.toAbsolutePath().toString(), perfParsedData.getAbsolutePath(), resultsTable);
    }

    @Override
    public void beforeTrial(BenchmarkParams params) {
        super.beforeTrial(params);
        if (!perfBinData.file().isDirectory() && !perfBinData.file().mkdirs()) {
            throw new IllegalStateException("Can't create folder " + perfBinData.getAbsolutePath());
        }
    }

    @Override
    public Collection<? extends Result> afterTrial(BenchmarkResult br, long pid, File stdOut, File stdErr) {
        try {
            BenchmarkResultMetaData md = br.getMetadata();
            if (md != null) {
                forkStartTimeMs = md.getStartTime();
            }
            return super.afterTrial(br, pid, stdOut, stdErr);
        } finally {
            TempFileUtils.removeDirectory(perfBinData.file().toPath());
        }
    }

    @Override
    protected PerfEvents readEvents(double skipMs, double lenMs) {
        Deduplicator<MethodDesc> dedup = new Deduplicator<>();
        Map<MethodDesc, AddressInterval> methods = new HashMap<>();
        Multiset<Long> events = new TreeMultiset<>();

        /*
         * BenchmarkResultMetaData captures the time when a fork was launched.
         * xctrace saves timestamps relative to the start of the tracing process.
         * It may take a considerable time to start xctrace (up to several seconds in some cases), so we
         * can't directly use measurementDelayMs.
         * However, xctrace trace's table of contents contains the timestamp corresponding to
         * the actual traced process start time. It could be used to correct measurementDelayMs.
         *
         *               /<-- delta -->/
         *              /             /
         *  time -------|-------------|------------------------------|----------->
         *              |             |                              |
         *       *fork launched*      |                     *measurements started*
         *        getStartTime()      |                      getMeasurementTime()
         *                      xctrace started java
         *                    tocHandler.getRecordStartMs()
         */
        long timeCorrectionMs = 0;
        if (shouldFixStartTime) {
            timeCorrectionMs = recordStartMs - forkStartTimeMs;
        }

        double correctedSkipNs = (skipMs - timeCorrectionMs) * 1e6;
        double endTimeNs = correctedSkipNs + lenMs * 1e6;
        XCTraceTableHandler handler = new XCTraceTableHandler(resultsTable, sample -> {
            double sampleTimeNs = sample.getTimeFromStartNs();
            if (sampleTimeNs < correctedSkipNs || sampleTimeNs >= endTimeNs) {
                return;
            }
            if (sample.getAddress() == 0L) {
                return;
            }
            events.add(sample.getAddress());

            // JIT sample
            if (sample.getBinary() != null) {
                String name = sample.getBinary();
                if (name.isEmpty()) {
                    // TODO
                    name = "[unknown]";
                    throw new IllegalStateException("Empty binary name");
                }
                MethodDesc method = dedup.dedup(MethodDesc.nativeMethod(sample.getSymbol(), name));

                methods.compute(method, (key, value) -> {
                    if (value == null) {
                        return new AddressInterval(sample.getAddress());
                    }
                    value.add(sample.getAddress());
                    return value;
                });
            }
        });
        handler.parse(perfParsedData.file());

        IntervalMap<MethodDesc> methodMap = new IntervalMap<>();
        methods.forEach((method, addresses) -> methodMap.add(method, addresses.getMin(), addresses.getMax()));

        Map<String, Multiset<Long>> allEvents = new TreeMap<>();
        assert requestedEventNames.size() == 1;
        allEvents.put(requestedEventNames.get(0), events);
        return new PerfEvents(requestedEventNames, allEvents, methodMap);
    }

    @Override
    protected String perfBinaryExtension() {
        return ".trace";
    }

    @Override
    public Collection<String> addJVMInvokeOptions(BenchmarkParams params) {
        return XCTraceUtils.recordCommandPrefix(perfBinData.getAbsolutePath(), template);
    }

    @Override
    public String getDescription() {
        return "macOS xctrace (Instruments) + PrintAssembly profiler";
    }

    private static class AddressInterval {
        private long min;
        private long max;

        public AddressInterval(long address) {
            min = address;
            max = address;
        }

        void add(long address) {
            min = Math.min(min, address);
            max = Math.max(max, address);
        }

        public long getMin() {
            return min;
        }

        public long getMax() {
            return max;
        }
    }
}
